name: All Tests

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - "*"

jobs:

  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd tests/unit
          python -m unittest test_my_utils


  run_func_tests:
    #TODO: Add micro-mamba and install matplotlib
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2
      - run: |
          pip install matplotlib
          pip install pandas
          cd tests/function
          bash test_calc.sh

  run_style_checks: # using pycodestyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd src
          pip install pycodestyle
          pycodestyle --max-line-length=120 my_utils.py