name: Unit Tests

on:
  pull_request:
    branches:
        - main
        - master
  push:
    branches:
        - main
        - master

jobs:

  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd test/unit
          python -m unittest test_my_utils


  run_func_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd test/function
          bash test_calc.sh

  run_style_checks: # using pycodestyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd src
          pip install pycodestyle
          pycodestyle --max-line-length=120 my_utils.py